-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Nayte CASCADE;
DROP TABLE IF EXISTS Tutkimus CASCADE;
DROP TABLE IF EXISTS Naytteenottopaikka CASCADE;
DROP TABLE IF EXISTS Kohde CASCADE;
DROP TABLE IF EXISTS Tutkija CASCADE;


